### PR TITLE
Add feature that support audio transcoding

### PR DESCRIPTION
**Pull request by RichardTamarisk**
* add encode_Audio(AVStream *inStream, StreamContext *encoder) function;
* add transcode_Audio(StreamContext *decoder, StreamContext *encoder) function;
* implement prepare_Encoder_Audio(StreamContext *decoder, StreamContext *encoder);
* add #include <libavutil/channel_layout.h>

### CODE REVIEW

**Comment by RichardTamarisk** [comment]
#7

**Comment by JackLau1222** [comment]
there are some conflict you need to resolve, plz check it

**Comment by JackLau1222** [comment]
> there are some conflict you need to resolve, plz check it

there are still some conflicts you need to resolve, please fix it firstly.

**Comment by RichardTamarisk** [comment]
> > there are some conflict you need to resolve, plz check it
> 
> there are still some conflicts you need to resolve, please fix it firstly.

ok, I'll resolve it out as soon as possible.

**Pull request closed without merging**
